---
apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: influxdb  
  namespace: monitoring
spec:  
  accessModes:  
  - ReadWriteOnce  
  resources:  
    requests:  
      storage: 100Gi
